1[features]
2seeds = false
3skip-lint = false
4
5[programs.localnet]
6recur_staking = "RECURXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx"
7
8[programs.devnet]
9recur_staking = "RECURXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx"
10
11[registry]
12url = "https://api.apr.dev"
13
14[provider]
15cluster  = "devnet"
16wallet   = "~/.config/solana/id.json"
17
18[scripts]
19test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
20
21[[test.validator.clone]]
22address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
23
